<?php

define('associate_access',			'acceso socios');
define('user_access',				'acceso usuarios');
define('contact',					'contacto');
define('login',						'entrar');
define('_exit',						'salir');
define('user',						'usuario');
define('users',						'usuarios');
define('bookings',					'reservas');
define('password',					'contraseña');
define('new_user',					'regístrate');
define('reset_pwd',					'¿olvidaste tu contraseña?');
define('wrong_login',				'usuario o contraseña incorrectos');
define('tries',						'intentos');
define('account_settings',			'configurar cuenta');
define('next_booking',				'próxima reserva');
define('pending_alerts',			'notificaciones pendientes');
define('search_users',				'buscar usuarios');
define('config_users',				'configuración usuarios');
define('create_new_user',			'crear nuevo usuario');
define('name',						'nombre');
define('associate_name',			'nombre socio');
define('associate_num',				'número socio');
define('search',					'buscar');
define('results',					'resultados');
define('shown',						'mostrados');
define('view',						'ver');
define('page',						'pág');	
define('all',						'todos');
define('to',						'a');
define('rows_per_page',				'resultados por página');
define('go_to',						'ir a pág.');
define('no_soc',					'nº soc.');
define('nickname',					'apodo');
define('phones',					'telfs.');
define('next_book',					'próx. reserva');
define('date_registered',			'fecha registro');
define('make_reservation_for',		'hacer reserva para');
define('user_details',				'detalles de usuario');
define('user_deleted',				'el usuario ha sido borrado');
define('user_blocked',				'el usuario ha sido bloqueado');
define('cant_make_reservation',		'no se pueden hacer reservas');
define('no_results_found',			'no se han econtrado resultados');
define('book_a_court',				'reserva una pista');
define('your_bookings',				'tus reservas');
define('today',						'hoy');
define('you_can_book_only',			'solo puedes reservar');
define('each_time',					'pistas a la vez');
define('prebook',					'pre-reserva');
define('confirmed',					'confirmada');
define('cancelled',					'cancelada');
define('expired',					'caducada');
define('waiting_players',			'esperando jugadores');
define('one',			'uno');
define('two',			'dos');
define('three',			'tres');
define('four',			'cuatro');
define('five',			'cinco');
define('six',			'seis');
define('seven',			'siete');
define('eight',			'ocho');
define('nine',			'nueve');
define('ten',			'diez');
define('eleven',		'once');
define('twelve',		'doce');
define('thirteen',		'trece');
define('fourteen',		'catorce');
define('fifteen',		'quince');
define('sixteen',		'dieciséis');
define('seventeen',		'diecisiete');
define('eighteen',		'dieciocho');
define('nineteen',		'diecinueve');
define('twenty',		'veinte');
define('plus',			'más');
define('by',			'por');
define('minus',			'menos');
define('between',		'entre');

define('error_user_or_password',	'El usuario o la contraseña son incorrectos');
define('write_user_name_pass',		'Escribe tu nombre de usuario y contraseña');

?>